### ISSUE TITLE
after arch_rebuild, why is there no Arch Migrator here

### ISSUE THREAD

**Issue by yangxingyu588** [conda-forge/r-tweenr-feedstock#15]
### Comment:

l've added` r-tweenr` to the [arch_rebuild.txt](https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/4822/files) file of [conda-forge-pinning-feedstock](https://github.com/conda-forge/conda-forge-pinning-feedstock), but why isn't auto build start here for linux-aarch64?

**Comment by mfansler** [comment]
Thanks for pointing this out! Not sure what went awry here. @conda-forge/arm-arch any thoughts?

In the meantime, I'm starting a manual migration with https://github.com/conda-forge/r-tweenr-feedstock/pull/16.

**Comment by mfansler** [comment]
There seems to be no evidence of a migration PR hitting the feedstock, but the bot seems convinced that it successfully migrated:

<img width="389" alt="Screen Shot 2023-08-22 at 11 43 44 PM" src="https://github.com/conda-forge/r-tweenr-feedstock/assets/1182216/9ff07e8a-1575-44e5-a6e2-9ff44b5038ed">
